name: Node CI

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install, build, and test
        run: |
          npm install -g yarn
          yarn
          docker pull cristianrgreco/ryuk:0.4.0
          docker pull zookeeper:3.7.0
          docker pull postgres:alpine
          yarn run ci
        env:
          CI: "true"

      - uses: codecov/codecov-action@v1.0.3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
